import Head from 'next/head'
import Hero from '../components/About/Hero'
import MTD from '../components/About/MTD'
import OC from '../components/About/OC'
import Footer from '../components/Footer'
import Header from '../components/Header'
import PreFooter from '../components/PreFooter'

const about = () => {
  return (
    <div>
        <Head>
            <title>myteam | About Us</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Hero />
        <MTD />
        <OC />
        <PreFooter />
        <Footer />
    </div>
  )
}

export default about