import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Home/Hero'
import SectionA from '../components/Home/SectionA'
import SectionB from '../components/Home/SectionB'
import PreFooter from '../components/PreFooter'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>myteam | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      <Hero />
      <SectionA />
      <SectionB />
      <PreFooter />
      <Footer />
    </div>
  )
}